version: 0.0
os: linux
files:
  - source: *.jar
    destination: /opt/app/
hooks:
#  AfterInstall:
#    - location: codedeploy/restartTomcat.sh
#      timeout: 300
#      runas: root
  ApplicationStart: 
    - location: scripts/appstart.sh
      timeout: 300
      runas: root
